version: "3"
services:
  db:
    image: postgres
    container_name: dictpress-dbcon
    volumes:
       - pgdatadir:/var/lib/postgresql
    env_file:
      - pg.secret.env
    ports:
      - "5432:5432"
volumes:
  pgdatadir:
